### PR TITLE
Overhaul

### PR DESCRIPTION
**Pull request by rclark**
My weekend/airplane rewrite. 

### Highlights:

- clear `require` access to high-level create, delete, update, info, save commands
- clear`require` access to all the nuts and bolts requests that cobble together into high-level commands
- consolidate CLI commands into a single utility
- 100% test coverage, much improved architecture for writing and maintaining tests
- during an update, prompts user to accept changeset details (which resources will be added, removed, modified, replaced) 
- asks you to provide bucket locations for saved configurations and uploaded templates instead of relying on janky inference and behind-the-scenes bucket generation

### Caveats

- made no effort to maintain the API, downstream integration may be tricky
- probably need to revisit the payload from stack info requests for better backwards compat
- used some es6 syntax in tests but avoided in production code -- is node 0.10.x support still required?

### ToDo

- override parameter values and saved config in create/update
- update in force-mode is not right
- get a sense for difficulty in downstream integration
- write documentation for commands.js
- rewrite readme.md

cc @mapbox/platform

### CODE REVIEW

**Comment by yhahn** [comment]
:+1:

**Comment by yhahn** [comment]
- https://github.com/mapbox/cfn-config/blob/rewrite/lib/commands.js#L451-L457

I think we'll want to preserve the ability to type in a specific config filename rather than forcing it to be named after `suffix`. We often save configs by `{suffix}-{region}`, `{suffix}-{region}-{deployPhase}` etc

**Comment by jakepruitt** [comment]
😐 seeing `MalformedXML: The XML you provided was not well-formed or did not validate against our published schema` when `actions.saveTemplate` is called during a `cfn-config update` for api-styles-staging using master:

```
cfn-config update staging ./cloudformation/api-styles.template.js --region us-east-1
```

@yhahn @rclark could one of you two reproduce this?

**Comment by rclark** [comment]
@jakepruitt this version of cfn-config requires you to set a template bucket. I've got a half-baked PR that I'll land today that'll provide a default value for this parameter.

In the meantime add

```
--template-bucket cfn-config-templates-$AWS_ACCOUNT_ID-us-east-1
```

I'll also try and make the error message you received a little more clear.

**Pull request merged**
