### PR TITLE
Update dependency inquirer v6.1.0

### PR DESCRIPTION
**Pull request by danmactough**
This version includes https://github.com/SBoudrias/Inquirer.js/pull/700, which enables a user to enter an empty input value for an input with a default value.

To enter an empty value, a user hits the backspace key when the input is empty. This clears the default value.

Demo (in combination with updating mbxcli):

2018-08-07-clear-defaults-2

@rclark

### CODE REVIEW

**Comment by danmactough** [comment]
Looks like this will require dropping support for node 4.

**Comment by danmactough** [comment]
If we really must maintain node 4 compatability, we could suggest backporting that change to inquirer to an older version, but with node 4 no longer getting security updates, dropping support seems prudent.

**Comment by rclark** [comment]
We definitely don't need to maintain node 4 support any longer. See https://github.com/mapbox/cfn-config/pull/164

**Comment by rclark** [comment]
Let's let @mapbox/assembly-line play out #164 first, then merge this one once they're done.

**Comment by danmactough** [comment]
Gotcha. I'll remove the conflicting edit to `.travis.yml` and hold tight.

**Comment by vsmart** [comment]
This was done in #164.

**Pull request closed without merging**
